### PR TITLE
UI

### PR DESCRIPTION
**Pull request by CoebeAustin**
fixed the issue regarding the assets in ddg

### CODE REVIEW

**Review by WhiteLicorice — CHANGES_REQUESTED** [review]
Do we really need the extra html and css files or can they be safely deleted? Remember that when we deploy the extension, users only download the userscript.js file.

**Comment by CoebeAustin** [comment]
Not really. they can be safely deleted.

**Comment by CoebeAustin** [comment]
HTML and CSS files deleted

**Review by WhiteLicorice — APPROVED** [review]
LGTM!!!

**Pull request merged**
